package com.example.demo.adapter.outbound.repository.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.demo.adapter.outbound.repository.LocalDateConverter;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@Getter
@Setter
@DynamoDBTable(tableName = "tb_pedidos")
public class PedidoEntity {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "hash_pedido")
    private UUID hashPedido;

    @DynamoDBAttribute(attributeName = "numero_pedido")
    private String numeroPedido;

    @DynamoDBAttribute(attributeName = "data_pedido")
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate dataPedido;

    @DynamoDBAttribute(attributeName = "status_pedido")
    private String status;

    @DynamoDBAttribute(attributeName = "valor_total")
    private String valorTotal;

    @DynamoDBAttribute(attributeName = "composicao")
    private List<ComposicaoEntity> composicaoEntity;

    @DynamoDBAttribute(attributeName = "cliente")
    private ClienteEntity cliente;

}
