version: '3.5'

services:
  tech-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-challenge:1
    container_name: tech-challenge
    restart: on-failure
    ports:
      - "8080:8080"
  localstack:
    container_name: dynamodb-local
    image: "amazon/dynamodb-local:latest"
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
